// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwhGOBlxR99UKwVmLx49bkzlFc6qYRrCI',
    appId: '1:915784461572:web:c39297d9a629a948e4f451',
    messagingSenderId: '915784461572',
    projectId: 'algorithmauth',
    authDomain: 'algorithmauth.firebaseapp.com',
    storageBucket: 'algorithmauth.appspot.com',
    measurementId: 'G-JMWDJ378Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2L9AXrTfAdprmGEOhNq4DmMTuk-_JcCk',
    appId: '1:915784461572:android:b033fc05117f7de8e4f451',
    messagingSenderId: '915784461572',
    projectId: 'algorithmauth',
    storageBucket: 'algorithmauth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEc0vKu4JPbdTXkNAg1PRQQeRj0oljI3U',
    appId: '1:915784461572:ios:5ccdc086e24e06c2e4f451',
    messagingSenderId: '915784461572',
    projectId: 'algorithmauth',
    storageBucket: 'algorithmauth.appspot.com',
    iosBundleId: 'com.example.finalmp',
  );
}
